study: # Configuration for training
  study_name: "cifar10"
  trials: 50
  epochs: 50 # Integer number for indicating the epochs for training target model.
  batch_size: 128 # Integer number for indicating batch size for training the target model.
  optimizer: SGD # String which indicates the optimizer.
  root: ./study

data: # Configuration for data
  dataset: cifar10 # String indicates the name of the dataset
  default_dist: True # Should custom training and testing dataset be used, if false f_train and f_test will be used
  f_train: 0.8 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.2 # Float number from 0 to 1 indicating the size of the test set
  augment: True 
  root: ./data # String about where to save the data.
